---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: emitter-ce-backend-trigger
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: services-res
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: notes-backend
      namespace: notes-app
