---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: processor-ce-trigger
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: Reminders
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: emitter-new-ce
