apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes-backend
  namespace: notes-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: harsha060201/notes-backend
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_DATABASE
              value: "notes-db"
            - name: DB_URI
              value: "mongodb://backend-mongodb-0.backend-mongodb.notes-app:27017"
            - name: KC_HOST
              value: "http://keycloak.notes-app.10.97.204.188.sslip.io"
            - name: SERVER_PORT
              value: "3001"
            - name: FUNC_PROCESSOR_URL
              value: "http://processor.notes-app.10.97.204.188.sslip.io"
            - name: FRONTEND_URL
              value: "http://notes-frontend.notes-app.10.97.204.188.sslip.io"
