apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes-backend
  namespace: notes-app
spec:
  template:
    spec:
      containers:
      - image: raxkumar/notes-backend
        ports:
          - containerPort: 3001
        env:
        - name: MONGODB_DATABASE
          value: "notes-db"
        - name: DB_URI
          value: "mongodb://backend-mongodb-0.backend-mongodb.notes-app:27017"
        - name: KC_HOST
          value: "http://172.17.0.2:30001"
        - name: SERVER_PORT
          value: "3001"
        readinessProbe:
            httpGet:
                path: /test
                port: http
            # initialDelaySeconds: 20
            # periodSeconds: 15
            # failureThreshold: 6
        livenessProbe:
            httpGet:
                path: /test
                port: http
            # initialDelaySeconds: 120