apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-player-3
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: quay.io/ruben/cloudevents-player:latest
