apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes-frontend
  namespace: notes-app
spec:
  template:
    spec:
      containers:
        - image: raxkumar/notes-frontend
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_OIDC_AUTHORITY
              value: "http://172.17.0.2:30001/realms/notes"
            - name: REACT_APP_OIDC_CLIENT_ID
              value: "notes"
            - name: REACT_APP_PROJECT_URL
              value: "http://notes-frontend.notes-app.10.99.157.216.sslip.io/"
            - name: REACT_APP_API_BASE_URL
              value: "http://notes-backend.notes-app.10.99.157.216.sslip.io"
