apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: new-notes-frontend
  namespace: notes-app
spec:
  template:
    spec:
      containers:
        - image: harsha060201/newnotesapp
          ports:
            - containerPort: 80
