apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes-frontend
  namespace: notes-app
spec:
  template:
    spec:
      containers:
        - image: raxkumar/notes-frontend
          ports:
            - containerPort: 80
