apiVersion: v1
kind: Service
metadata:
    name: keycloak
    namespace: notes-app
    labels:
        app: keycloak
spec:
    ports:
        - name: http
          port: 9080
          targetPort: 8080
          nodePort: 30001
    type: NodePort
    publishNotReadyAddresses: true
    selector:
        app: keycloak
