apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: example-backend-sink-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: example-backend
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker